; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=sycl-kernel-equalizer -sycl-builtin-alias=%p/../Inputs/BuiltinAliases.gen -S %s -enable-debugify -disable-output 2>&1 | FileCheck -check-prefix=DEBUGIFY %s
; RUN: opt -passes=sycl-kernel-equalizer -sycl-builtin-alias=%p/../Inputs/BuiltinAliases.gen -S %s | FileCheck %s

define void @kernel() {
; CHECK-LABEL: @kernel(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[C0:%.*]] = call i8 @_Z19sub_group_broadcastcj(i8 0, i32 0)
; CHECK-NEXT:    [[C1:%.*]] = call <3 x half> @_Z19sub_group_broadcastDv3_Dhj(<3 x half> zeroinitializer, i32 0)
; CHECK-NEXT:    [[C2:%.*]] = call i32 @_Z13sub_group_alli(i32 0)
; CHECK-NEXT:    [[C3:%.*]] = call i32 @_Z13sub_group_anyi(i32 0)
; CHECK-NEXT:    [[C4:%.*]] = call i32 @_Z20sub_group_reduce_maxi(i32 0)
; CHECK-NEXT:    [[C5:%.*]] = call i32 @_Z28sub_group_scan_inclusive_addi(i32 0)
; CHECK-NEXT:    [[C6:%.*]] = call i32 @_Z28sub_group_scan_exclusive_mini(i32 0)
; CHECK-NEXT:    ret void
;
entry:
  %c0 = call i8 @_Z25intel_sub_group_broadcastcj(i8 0, i32 0)
  %c1 = call <3 x half> @_Z31sub_group_non_uniform_broadcastDv3_Dhj(<3 x half> zeroinitializer, i32 0)
  %c2 = call i32 @_Z25sub_group_non_uniform_alli(i32 0)
  %c3 = call i32 @_Z25sub_group_non_uniform_anyi(i32 0)
  %c4 = call i32 @_Z26intel_sub_group_reduce_maxi(i32 0)
  %c5 = call i32 @_Z34intel_sub_group_scan_inclusive_addi(i32 0)
  %c6 = call i32 @_Z34intel_sub_group_scan_exclusive_mini(i32 0)
  ret void
}

declare i8 @_Z25intel_sub_group_broadcastcj(i8 %x, i32 %sub_group_local_id)
declare <3 x half> @_Z31sub_group_non_uniform_broadcastDv3_Dhj(<3 x half> %x, i32 %sub_group_local_id)
declare i32 @_Z25sub_group_non_uniform_alli(i32 %predicate)
declare i32 @_Z25sub_group_non_uniform_anyi(i32 %predicate)
declare i32 @_Z26intel_sub_group_reduce_maxi(i32 %predicate)
declare i32 @_Z34intel_sub_group_scan_inclusive_addi(i32 %predicate)
declare i32 @_Z34intel_sub_group_scan_exclusive_mini(i32 %predicate)

; DEBUGIFY-NOT: WARNING
