; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -passes=sycl-kernel-equalizer -S %s -enable-debugify -disable-output 2>&1 | FileCheck -check-prefix=DEBUGIFY %s
; RUN: opt -passes=sycl-kernel-equalizer -S %s | FileCheck %s

define void @kernel() {
; CHECK-LABEL: @kernel(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[SG_LID:%.*]] = call i32 @_Z22get_sub_group_local_idv()
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @_Z28sub_group_ballot_bit_extractDv4_jj(<4 x i32> zeroinitializer, i32 [[SG_LID]])
; CHECK-NEXT:    ret void
;
entry:
  %c0 = call i32 @_Z24sub_group_inverse_ballotDv4_j(<4 x i32> zeroinitializer)
  ret void
}

declare i32 @_Z24sub_group_inverse_ballotDv4_j(<4 x i32> %value)

; DEBUGIFY-NOT: WARNING
