; RUN: SATest -BUILD --config=%s.cfg -tsize=1 -llvm-option=-print-before=sycl-kernel-analysis -stop-before-jit 2>&1 | FileCheck %s

; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomiciP{{.*}}ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomiciP{{.*}}ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomiciP{{.*}}ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomiciP{{.*}}ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicjP{{.*}}jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicjP{{.*}}jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicjP{{.*}}jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicjP{{.*}}jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomiclP{{.*}}ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomiclP{{.*}}ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomiclP{{.*}}ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomiclP{{.*}}ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicmP{{.*}}mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicmP{{.*}}mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicmP{{.*}}mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicmP{{.*}}mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicfP{{.*}}ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicfP{{.*}}ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicfP{{.*}}ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicfP{{.*}}ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicdP{{.*}}dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicdP{{.*}}dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicdP{{.*}}dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakP{{.*}}VU7_AtomicdP{{.*}}dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomiciP{{.*}}ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomiciP{{.*}}ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomiciP{{.*}}ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomiciP{{.*}}ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiciP{{.*}}ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicjP{{.*}}jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicjP{{.*}}jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicjP{{.*}}jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicjP{{.*}}jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicjP{{.*}}jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomiclP{{.*}}ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomiclP{{.*}}ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomiclP{{.*}}ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomiclP{{.*}}ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomiclP{{.*}}ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicmP{{.*}}mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicmP{{.*}}mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicmP{{.*}}mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicmP{{.*}}mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicmP{{.*}}mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicfP{{.*}}ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicfP{{.*}}ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicfP{{.*}}ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicfP{{.*}}ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicfP{{.*}}ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicdP{{.*}}dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicdP{{.*}}dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicdP{{.*}}dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongP{{.*}}VU7_AtomicdP{{.*}}dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitP{{.*}}VU7_AtomicdP{{.*}}dd12memory_orderS4_12memory_scope

; CHECK: Test program was successfully built.
