; RUN: SATest -BUILD --config=%s.cfg -tsize=1 -llvm-option=-print-before=sycl-kernel-builtin-import -stop-before-jit 2>&1 | FileCheck %s

; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomiciPU3AS4ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomiciPU3AS4ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomiciPU3AS4ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomiciPU3AS4ii
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicjPU3AS4jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicjPU3AS4jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicjPU3AS4jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicjPU3AS4jj
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomiclPU3AS4ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomiclPU3AS4ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomiclPU3AS4ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomiclPU3AS4ll
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicmPU3AS4mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicmPU3AS4mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicmPU3AS4mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicmPU3AS4mm
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicfPU3AS4ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicfPU3AS4ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicfPU3AS4ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicfPU3AS4ff
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicdPU3AS4dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicdPU3AS4dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicdPU3AS4dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z28atomic_compare_exchange_weakPU3AS4VU7_AtomicdPU3AS4dd
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_
; CHECK: call {{.*}}@_Z37atomic_compare_exchange_weak_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomiciPU3AS4ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomiciPU3AS4ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomiciPU3AS4ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomiciPU3AS4ii
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiciPU3AS4ii12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicjPU3AS4jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicjPU3AS4jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicjPU3AS4jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicjPU3AS4jj
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicjPU3AS4jj12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomiclPU3AS4ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomiclPU3AS4ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomiclPU3AS4ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomiclPU3AS4ll
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomiclPU3AS4ll12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicmPU3AS4mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicmPU3AS4mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicmPU3AS4mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicmPU3AS4mm
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicmPU3AS4mm12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicfPU3AS4ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicfPU3AS4ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicfPU3AS4ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicfPU3AS4ff
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicfPU3AS4ff12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicdPU3AS4dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicdPU3AS4dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicdPU3AS4dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_12memory_scope
; CHECK: call {{.*}}@_Z30atomic_compare_exchange_strongPU3AS4VU7_AtomicdPU3AS4dd
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_
; CHECK: call {{.*}}@_Z39atomic_compare_exchange_strong_explicitPU3AS4VU7_AtomicdPU3AS4dd12memory_orderS4_12memory_scope

; CHECK: Test program was successfully built.
